import type { TinaField } from "tinacms";
export function data_fileFields() {
  return [
    {
      type: "string",
      name: "Items",
      label: "Items",
      list: true,
    },
  ] as TinaField[];
}
export function service_providerFields() {
  return [
    {
      type: "string",
      name: "org",
      label: "Organization name",
      required: true,
    },
    {
      type: "boolean",
      name: "highlight",
      label: "Highlight",
    },
    {
      type: "string",
      name: "program",
      label: "Program/clinic name (if applicable)",
    },
    {
      type: "string",
      name: "website",
      label: "Website",
    },
    {
      type: "string",
      name: "email",
      label: "Email",
    },
    {
      type: "string",
      name: "facebook",
      label: "Facebook",
    },
    {
      type: "string",
      name: "twitter",
      label: "Twitter",
    },
    {
      type: "string",
      name: "instagram",
      label: "Instagram",
    },
    {
      type: "string",
      name: "linkedin",
      label: "Linkedin",
    },
    {
      type: "string",
      name: "youtube",
      label: "Youtube",
    },
    {
      type: "string",
      name: "tiktok",
      label: "Tiktok",
    },
    {
      type: "string",
      name: "medium",
      label: "Medium",
    },
    {
      type: "string",
      name: "best_way_to_contact",
      label: "Best way to contact",
      list: true,
      options: ["Phone", "Email", "Website"],
    },
    {
      type: "string",
      name: "payment_types",
      label: "Payment types (clinical)",
      list: true,
      options: [
        "1199SEIU",
        "Out-of-network insurance",
        "Any insurance",
        "Aetna",
        "Affinity",
        "American Behavioral",
        "Amerigroup",
        "AmeriHealth",
        "Beacon Health",
        "Blue Care Network",
        "Blue Cross/Blue Shield",
        "CareFirst",
        "CDPHP",
        "Child Health Plus",
        "Cigna",
        "Clover Medicare",
        "Aetna (Columbia University employees only)",
        "ComPsych",
        "EmblemHealth",
        "Fidelis",
        "HealthFirst",
        "Hotel 6",
        "Humana",
        "Magna Care",
        "Medicaid",
        "Medical Mutual",
        "Medicare",
        "MetroPlus",
        "Military OneSource",
        "Multiplane",
        "MVP",
        "N/A",
        "New Directions",
        "UHC (New School employees only)",
        "Wellfleet (NYU employees only)",
        "Optum",
        "Oscar",
        "Oxford",
        "SMG Wellcare Medicare",
        "Third-party insurance",
        "Traditional Medicare",
        "TRICARE",
        "TriWest",
        "UHC UMR (Mount Sinai employees only)",
        "UnitedHealthcare",
        "VNS Choice Medicare",
      ],
    },
    {
      type: "boolean",
      name: "sliding_scale_clinical",
      label: "Sliding scale (clinical)",
    },
    {
      type: "string",
      name: "payment_info_clinical",
      label: "Payment info (clinical)",
      ui: {
        component: "textarea",
      },
    },
    {
      type: "string",
      name: "payment_types_non_clinical",
      label: "Payment types (non-clinical)",
      list: true,
      options: [
        "Out-of-Network Insurances",
        "Any insurance",
        "N/A",
        "No insurance necessary",
        "Sliding scale fee for patients without insurance",
        "Third-party insurance",
      ],
    },
    {
      type: "boolean",
      name: "sliding_scale_non_clinical",
      label: "Sliding scale (non-clinical)",
    },
    {
      type: "string",
      name: "payment_info_non_clinical",
      label: "Payment info (non-clinical)",
      ui: {
        component: "textarea",
      },
    },
    {
      type: "boolean",
      name: "ada_compliant",
      label: "ADA compliant",
    },
    {
      type: "string",
      name: "telehealth",
      label: "Telehealth service",
      options: ["Yes", "No", "Not applicable"],
    },
    {
      type: "string",
      name: "tags",
      label: "Tags",
      list: true,
      ui: {
        component: "tags",
      },
    },
    {
      type: "string",
      name: "client_requirements",
      label: "Client requirements",
    },
    {
      type: "string",
      name: "age_groups",
      label: "Age groups",
      list: true,
      options: [
        "Adults (18+)",
        "Adults (19 to 64)",
        "All",
        "Children (5+)",
        "Children (6 to 10)",
        "Preteens and Tweens (11 to 13)",
        "Seniors (55+)",
        "Seniors (60+)",
        "Seniors (65+)",
        "Toddlers and Preschoolers (0 to 5)",
        "Youth and Teenagers (13+)",
        "Youth and Teenagers (14 to 19)",
      ],
    },
    {
      type: "object",
      name: "locations",
      label: "Locations",
      list: true,
      fields: [
        {
          type: "string",
          name: "address",
          label: "Physical address",
          ui: {
            component: "textarea",
          },
        },
        {
          type: "string",
          name: "latLng",
          label: "latitude, longitude",
        },
        {
          type: "string",
          name: "boroughs",
          label: "Boroughs",
          list: true,
          options: [
            "Confidential Location",
            "Online",
            "Bronx",
            "Brooklyn",
            "Manhattan",
            "Queens",
            "Staten Island",
          ],
        },
        {
          type: "string",
          name: "phone_number",
          label: "Phone number",
        },
        {
          type: "string",
          name: "services",
          label: "Clinical services",
          list: true,
          options: [
            "Nutrition counseling for disordered eating, eating disorders, and medical conditions",
            "Art therapy",
            "Asian bi-cultural mental health services",
            "Behavioral services",
            "Brainspotting",
            "Connections to Care Program",
            "Drama Therapy",
            "Free mental health services",
            "Internal Family Systems Therapy",
            "Medication management",
            "Mental health services",
            "Multi-lingual and multi-cultural counseling",
            "Music therapy",
            "Outpatient and inpatient mental health services",
            "Outpatient mental health services",
            "Personalized Recovery Services (PROS)",
            "Play Therapy",
            "Psychiatric day treatment",
            "Psychiatric evaluation",
            "Psychological testing and assessment",
            "Psychotherapy",
            "Sensory Resonance Modalities",
            "Substance Abuse Services",
            "Support Groups",
            "Substance use/addiction and support services",
            "Referrals to clinical services ",
          ],
        },
        {
          type: "boolean",
          name: "psychotherapy",
          label: "Psychotherapy",
        },
        {
          type: "string",
          name: "psychotherapy_specialties",
          label: "Psychotherapy specialties",
          list: true,
          options: [
            "Addiction/recovery",
            "Adoption and foster care",
            "Alcohol abuse",
            "Anger management",
            "Anxiety",
            "ADHD",
            "Attachment issues",
            "Autism spectrum disorder",
            "Behavioral issues",
            "Bipolar disorder",
            "Caregiver stress and support",
            "Chronic illness",
            "Chronic pain",
            "Codependency",
            "Coping skills",
            "Cultural adjustment",
            "Dementia",
            "Depression",
            "Developmental disorders",
            "Divorce and separation",
            "Domestic abuse",
            "Domestic violence",
            "Drug abuse",
            "Eating disorders",
            "Emotional disturbance",
            "Family conflict",
            "Gambling",
            "Grief, loss, and bereavement",
            "Hoarding",
            "Identity development",
            "Infertility",
            "Insomnia and sleep issues",
            "Intellectual disability",
            "Internet addiction",
            "Learning disabilities",
            "LGBTQIA, gender, and sexual identity",
            "Medication management",
            "Men's issues",
            "Mood disorders",
            "Obesity",
            "Obsessive compulsive disorder",
            "Oppositional defiance",
            "Panic attacks/disorder",
            "Parenting",
            "Personality disorders",
            "Phobias/fears",
            "Pregnancy, perinatal, and postpartum mental health",
            "Premarital/marital",
            "Racial and cultural identity",
            "Relationship issues",
            "Schizophrenia",
            "Self-esteem",
            "Self-harming",
            "Sexual abuse",
            "Sexual addiction",
            "Sexual harassment and assault",
            "Sexual health/dysfunction",
            "Spirituality",
            "Stress",
            "Substance abuse",
            "Suicidal ideation",
            "Teen violence",
            "Transracial Adoption",
            "Trauma/PTSD",
            "Weight loss",
            "Women's issues",
          ],
        },
        {
          type: "string",
          name: "psychotherapy_types",
          label: "Psychotherapy types",
          list: true,
          options: [
            "Every client is unique, and a custom approach is explored and co-created with each individual.",
            "Other ",
            "Accelerated Experiential Dynamic Psychotherapy",
            "Acceptance and Commitment Therapy",
            "Art Therapy",
            "Client Centered",
            "Cognitive Behavioral Therapy",
            "Cognitive Processing Therapy",
            "Compassion-Focused Therapy (CFT)",
            "Couples Therapy",
            "Dialectical Behavioral Therapy",
            "Ego Supportive",
            "EMDR",
            "Emotion Focused Therapy",
            "Family therapy",
            "Gestalt approach with utilizing all forms of arts and body awareness",
            "Group therapy",
            "Humanistic",
            "Internal Family Systems",
            "Integrative Therapy",
            "Interpersonal",
            "Mindfulness-based",
            "Narrative therapy",
            "Person-centered Therapy",
            "Psychoanalysis",
            "Psychodynamic",
            "Relational Therapy",
            "Solution-focused Therapy",
            "Somatic IFS Therapy",
            "Somatic Psychotherapy",
            "Strengths based",
            "Supportive Therapy",
            "Trauma-informed",
            "Trauma Art Narrative Therapy",
          ],
        },
        {
          type: "string",
          name: "non_clinical_services",
          label: "Non-clinical services",
          list: true,
          options: [
            "Acupressure/Self Acupressure ",
            "Acupuncture",
            "Advocacy",
            "After-school",
            "Aromatherapy",
            "Assistance with health insurance (pre and post enrollment issues)",
            "Awareness and stigma campaigns",
            "Brainspotting",
            "Breathwork",
            "Career coaching",
            "Case management",
            "Case management for seniors",
            "Chakra balancing",
            "Clinical supervision",
            "Coaching",
            "Consulting",
            "Crisis hotline",
            "Crisis intervention and management",
            "Domestic violence counseling",
            "Energy healing",
            "Entitlement/benefits/SNAP assistance",
            "ESL classes",
            "Executive coaching and consulting",
            "Family support",
            "Flower essence therapy",
            "Financial literacy",
            "Food pantry",
            "Healing Sessions",
            "High school equivalency classes",
            "Hypnotherapy",
            "Indigenous healing methodologies",
            "Inner child work",
            "Know your rights workshops",
            "Life Coaching",
            "Lifestyle wellness training",
            "Home delivered meals",
            "Massage",
            "Meditation/mindfulness practices",
            " Mentoring/coaching in self-exploration and self-adjustment",
            "Mindset and goal setting",
            "Music school",
            "Online self-help modules",
            "Peer support groups",
            "Pottery school",
            "Pranic Healing",
            "Psychoeducation",
            "Qigong",
            "Ritual/ceremony practices",
            "Screening, counseling, and benefits support",
            "Senior centers ",
            "Shamanic healing",
            "Smoking cessation",
            "Somatic therapy",
            "Sound and embodied movement practices",
            "Sound Healing",
            "Storytelling & expressive art processing",
            "Supported housing",
            "Support groups for seniors",
            "Reflexology",
            "Reiki",
            "Tai Chi",
            "Trauma-informed life coaching",
            "Workshops and trainings",
            "Yoga",
          ],
        },
        {
          type: "string",
          name: "credentials",
          label: "Credentials",
          list: true,
          options: [
            "RD (Registered Dietitian)",
            "MD (Doctor of Medicine)",
            "LCADAC (Licensed Clinical Alcohol & Drug Abuse Counselor)",
            "LCSW (Licensed Clinical Social Worker)",
            "Licensed Creative Arts Therapist",
            "Licensed Psychiatrist",
            "Licensed Psychoanalyst",
            "Licensed Psychologist (PhD/PsyD)",
            "LMFT (Licensed Marriage and Family Therapist)",
            "LMHC (Licensed Mental Health Counselor)",
            "LMSW (Licensed Master Social Worker)",
            "LPC (Licensed Professional Counselor)",
            "Psychiatric Mental Health Nurse Practitioner",
          ],
        },
        {
          type: "string",
          name: "trainings",
          label: "Trainings",
          ui: {
            component: "textarea",
          },
        },
        {
          type: "string",
          name: "languages",
          label: "Languages",
          list: true,
          options: [
            "Arabic",
            "Arabic (Egyptian)",
            "Arabic (Gulf dialects)",
            "Arabic (Levantine)",
            "Arabic (Moroccan)",
            "Arabic (Yemeni)",
            "Bangla",
            "Bhutanese",
            "Burmese",
            "Chinese (Cantonese)",
            "Chinese (Fujianese)",
            "Chinese (Fuzhounese)",
            "Chinese (Hakka)",
            "Chinese (Mandarin)",
            "Chinese (Shanghainese)",
            "Chinese (Taiwanese)",
            "Chinese (Teochew)",
            "Chinese (Toishanese)",
            "English",
            "German",
            "Gujarati",
            "Hindi",
            "Indonesian",
            "Japanese",
            "Khmer",
            "Korean",
            "Laotian",
            "Malayalam",
            "Marathi",
            "Nepali",
            "Pashto",
            "Persian Dari",
            "Punjabi",
            "Sign Language",
            "Spanish",
            "Tagalog",
            "Tamil",
            "Telegu",
            "Thai",
            "Turkish",
            "Vietnamese",
            "Urdu",
          ],
        },
        {
          type: "string",
          name: "new_clients",
          label: "New clients",
          options: ["Yes", "No", "Not applicable"],
        },
        {
          type: "string",
          name: "new_clients_detail",
          label: "New clients detail",
          ui: {
            component: "textarea",
          },
        },
        {
          type: "string",
          name: "parking",
          label: "Parking",
          options: ["Yes", "No", "Street parking"],
        },
        {
          type: "object",
          name: "public_transportation",
          label: "Public transportation options",
          list: true,
          fields: [
            {
              type: "string",
              name: "transport_option",
              label: "Transport option",
            },
          ],
        },
        {
          type: "string",
          name: "staff_gender",
          label: "Gender Identification of Provider(s)",
          list: true,
          options: [
            "Female",
            "Male",
            "Genderqueer",
            "Gender-neutral",
            "Gender nonconforming",
            "Nonbinary",
            "Transgender",
            "Other",
          ],
        },
        {
          type: "object",
          name: "hours_of_operation",
          label: "Hours of operation",
          list: true,
          fields: [
            {
              type: "string",
              name: "day_hours",
              label: "Days hours",
            },
          ],
        },
      ],
    },
    {
      type: "image",
      name: "image",
      label: "Image",
    },
  ] as TinaField[];
}
